[package]
name = "api"
version = "0.1.0"
edition = "2024"

[dependencies]
prost = "0.14.3"
prost-types = "0.14.3"
tonic = "0.14.3"
tonic-prost = "0.14.3"

[build-dependencies]
tonic-prost-build = "0.14.3"
